### ISSUE TITLE
weird problem caused by save modifier_id

### ISSUE THREAD

**Issue by holden** [mongoid/mongoid-history#57] opened 2013-01-27 08:17 UTC
I had a problem that caused all my older records to get "modified" by the same user regardless of the current_user.  After looking around at why only older records had this behavior and new records were recording the correct modifier I discovered that the old records all had a saved "modifier_id" on the root document itself (not the history tracks, those should have it) and the new ones had nil.

That seemed to fix it.  Should there be a modifier_id?  I'm assuming it's not suppose to have a permanent value on the root document itself (just the history tracks)?

**Comment by dblock** [comment] 2018-06-20 13:43
Closing because this is old and doesn't have a repro. Please reopen if you can reproduce.

**Closed by dblock** 2018-06-20 13:43 UTC
Labels: needs info
